"use client";
import { DM_Sans } from "next/font/google";
import { usePathname } from "next/navigation"; // Import usePathname
import "./globals.css";
import { Footer, Header } from "@/components";
import ProtectRoute from "@/components/ProtectRoute";

const dmSans = DM_Sans({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname(); // Get the current path

  const showHeaderAndFooter = pathname !== "/Login"; 
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <ProtectRoute>
        {showHeaderAndFooter && <Header />}
         
         {children}

         {showHeaderAndFooter && <Footer />}
        </ProtectRoute>
          
        
      </body>
    </html>
  );
}
